#!/bin/sh

if [ -z "$1" ]; then
  if [ -e $HOME/.tmuxmouse ]; then
    __mode='off'
  else
    __mode='on'
  fi
else
  __mode=$1
fi

case $__mode in
  on)
    touch $HOME/.tmuxmouse
    echo "Activating tmux mouse support."
    ;;
  off)
    rm -f $HOME/.tmuxmouse
    echo "Deactivating tmux mouse support."
    ;;
  *)
    echo "Uknown mode: $__mode"
    exit 1
    ;;
esac

tmux set -g mode-mouse $__mode >/dev/null 2>&1
tmux set -g mouse-select-pane $__mode  >/dev/null 2>&1
tmux set -g mouse-select-window $__mode  >/dev/null 2>&1
tmux set -g mouse-resize-pane $__mode  >/dev/null 2>&1

exit 0
