#!/bin/zsh

_dots=(
  emacs
  gnus
  tmux.conf
  zsh zshenv zshrc zshalii zshcomplete
  )

for f in $_dots; do
  [[ ! -e $f ]] && continue
  if [[ -e $HOME/.$f ]]; then
    rm -rf $HOME/.$f.bak
    mv $HOME/.$f $HOME/.$f.bak
  fi
  cp -R $f $HOME/.$f
done

[[ -d $HOME/bin ]] || mkdir $HOME/bin
cp -R noarch $HOME/bin
