#!/bin/sh

_thisdir=`pwd`

for _rcfile in emacs bash_profile tmux.conf ; do
	[ -e "$HOME/.$_rcfile" ] && mv -f "$HOME/.$_rcfile" "$HOME/.$_rcfile.bak"
	ln -s "$_thisdir/$_rcfile" "$HOME/.$_rcfile"
done

mkdir -p $HOME/bin
cp -R noarch $HOME/bin

if which zsh >/dev/null ; then
	[ -e "$HOME/.zprezto" ] || git clone --recursive \
		https://github.com/nickvargish/prezto.git \
		"$HOME/.zprezto"
	$HOME/.zprezto/runcoms/linkdots
fi

