#!/bin/sh

thisdir=`pwd`

for rcfile in emacs bash_profile tmux.conf ; do
	[ -e "$HOME/.$rcfile" ] && mv -f "$HOME/.$rcfile" "$HOME/.$rcfile.bak"
	ln -s "$thisdir/$rcfile" "$HOME/.$rcfile"
done

mkdir -p $HOME/bin
cp -R noarch $HOME/bin

if which zsh >/dev/null ; then
	[ -e "$HOME/.zprezto" ] || git clone --recursive \
		https://github.com/nickvargish/prezto.git \
		"$HOME/.zprezto"
	$HOME/.zprezto/runcoms/linkdots
fi

